name = "prototype-app"

[env.staging]
name = "prototype-app-staging"
route = "staging.prototype-app.pages.dev/*"
workers_dev = true
compatibility_date = "2023-10-02"

[env.production]
name = "prototype-app"
route = "prototype-app.pages.dev/*"
workers_dev = true
compatibility_date = "2023-10-02"

[site]
bucket = "./dist"
pages_build_output_dir = "dist"
